apiVersion: v1
kind: Pod
metadata:
  name: pod3
  labels:
    app: application3
spec:
  containers:
  - name: httpd
    image: httpd
    ports: 
    - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: service3
spec:
  type: NodePort 
  ports:
  - port: 9090
    nodePort: 30003
    targetPort: 80
  selector:
   app: application3
  
---

